# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - architecture_linter

architecture_linter:
  excludes:
    - "**.g.dart"

  lint_severity: warning

  layers:
    - &infrastructureLayer
      name: "Infrastructure"
      pathRegex:
        source: "(infrastructure)"
    - &domainLayer
      name: "Domain"
      pathRegex:
        source: "(domain)"
    - &presentationLayer
      name: "Presentation"
      pathRegex:
        source: "(presentation)"
    - &repository
      name: "repository"
      pathRegex:
        source: "(repository)"

  layers_config:
    - layer: *repository
      severity: info

  bannedImports:
    - layer: *domainLayer
      banned:
        - *presentationLayer
    - layer: *presentationLayer
      banned:
        - *infrastructureLayer
    - layer: *infrastructureLayer
      banned:
        - *presentationLayer
