name: architecture_linter
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: 5.2.0
  analyzer_plugin: 0.11.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
