name: architecture_linter
description: Software analytics tool that helps developers analyse and improve project architecture structure.
homepage: https://github.com/Iteo/architecture_linter
repository: https://github.com/Iteo/architecture_linter
version: 0.0.10

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: ">=4.1.0 <6.0.0"
  analyzer_plugin: ">=0.10.0 <0.12.0"
  yaml: ^3.1.0
  collection: ^1.16.0
  glob: ^2.0.1
  args: ^2.3.1
  path: ^1.8.3
  file: ^6.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mocktail: ^0.3.0