name: architecture_linter
description: Software analytics tool that helps developers analyse and improve project architecture structure.
homepage: https://github.com/Iteo/architecture_linter
repository: https://github.com/Iteo/architecture_linter
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: ">=5.1.0 <5.3.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  yaml: ^3.1.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
